version: "3.5"

services:
  api01: &api
    image: matheusmr95/rinha-de-backend-2024-q1:latest
    container_name: rinha-api-01
    hostname: api01
    ports:
      - 8081:9999
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api02:
    <<: *api
    container_name: rinha-api-02
    hostname: api02
    ports:
      - 8082:9999

  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  db:
    image: postgres:latest
    container_name: rinha-db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinhadb
    volumes:
      - ./src/main/resources/migration/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "250MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1