version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./src/main/resources/migration/script.sql:/docker-entrypoint-initdb.d/script.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pg_admin_data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  postgres_data: {}
  pg_admin_data: {}